spring:
  profiles:
    active: prod
  application:
    name: user-center
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 逻辑正常
